'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var INITIALIZE_PAGINATOR = exports.INITIALIZE_PAGINATOR = 'INITIALIZE_PAGINATOR';
var PREVIOUS_PAGE = exports.PREVIOUS_PAGE = 'PREVIOUS_PAGE';
var NEXT_PAGE = exports.NEXT_PAGE = 'NEXT_PAGE';
var GO_TO_PAGE = exports.GO_TO_PAGE = 'GO_TO_PAGE';
var SET_PAGE_SIZE = exports.SET_PAGE_SIZE = 'SET_PAGE_SIZE';
var FETCH_RECORDS = exports.FETCH_RECORDS = 'FETCH_RECORDS';
var RESULTS_UPDATED = exports.RESULTS_UPDATED = 'RESULTS_UPDATED';
var RESULTS_UPDATED_ERROR = exports.RESULTS_UPDATED_ERROR = 'RESULTS_UPDATED_ERROR';
var TOGGLE_FILTER_ITEM = exports.TOGGLE_FILTER_ITEM = 'TOGGLE_FILTER_ITEM';
var SET_FILTER = exports.SET_FILTER = 'SET_FILTER';
var SORT_CHANGED = exports.SORT_CHANGED = 'SORT_CHANGED';
var UPDATING_ITEM = exports.UPDATING_ITEM = 'UPDATING_ITEM';
var UPDATE_ITEM = exports.UPDATE_ITEM = 'UPDATE_ITEM';
var REMOVING_ITEM = exports.REMOVING_ITEM = 'REMOVING_ITEM';
var REMOVE_ITEM = exports.REMOVE_ITEM = 'REMOVE_ITEM';